### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by mjmdavis** [jplattel/PyMoves#3]
Seems that the **init** method is not indented correctly.

Also, the formatting is not PEP8 compliant. This makes it difficult to work with the file if your editor is set up for 4 space indentation.
http://legacy.python.org/dev/peps/pep-0008/#indentation

**Comment by jplattel** [comment]
Had to use this library for another project so I took it up to fix it, the latest commit is now pep8 compliant 👍
