### ISSUE TITLE
Issue requesting access token/authentication

### ISSUE THREAD

**Issue by Andreilys** [jplattel/PyMoves#4]
After receiving the code from approving the application to have access to my Moves data I get the following error:

 raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'access_token?grant_type=authorization_code&code=[ommited]&client_id=[ommited]&client_secret=[ommited]&redirect_uri=https://example.com/old/path'

**Comment by salmankhalid99** [comment]
This is because the URL is missing in the start for the function to get "Access Token", attach the move.txt
[moves.txt](https://github.com/jplattel/PyMoves/files/1373371/moves.txt)
 file  with some changes on the txt.

**Comment by jplattel** [comment]
Hi @Andreilys and @salmankhalid99 I've updated the library a bit, still untested but it should work properly now :)
