### ISSUE TITLE
Retrieve the authorization code

### ISSUE THREAD

**Issue by salmankhalid99** [jplattel/PyMoves#5]
I am able to get the authorization code when the user enters the PIN in the app and is redirected to the callback URI. I want to know how can I capture this part (retrieve the authorization code) without copying from the browser as the potential user will be doing this remotely in real world scenario.

**Comment by jplattel** [comment]
Normally the server would get the code and fetch the access_token instead of copying, that's what de callback url is for, you redirect this to your own server.

I'm closing this because it is not an issue with the library itself, but rather how you implement the OAuth flow.
